# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b36dc97b5a8c69bc7eb2dd0686d2812439f6644150aa6bc39371aa11045409e8bf25dcef33ee467cd4faecc50aa9e63f7b01c2e8b514d2329947224efc9b2af

test:
  secret_key_base: eeadaa511a75d4f9ae14003d6a25ab9aa4a67bcd23c4233a97ed4373282e1213760b1889baf9c1e184a84151bff12e3b5d497e7f2dc780d1bf1dc212b3464b3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
